import { useState } from "react";
import { motion } from "framer-motion";
import { FileDown, Loader2, CheckCircle } from "lucide-react";
import jsPDF from "jspdf";

interface ReportData {
  image?: string;
  type?: string;
  score?: number;
  solutions?: string[];
}

const ReportGenerator = ({ data }: { data?: ReportData }) => {
  const [generating, setGenerating] = useState(false);
  const [done, setDone] = useState(false);

  const generate = async () => {
    setGenerating(true);
    setDone(false);

    try {
      const pdf = new jsPDF();
      const w = pdf.internal.pageSize.getWidth();

      // Header
      pdf.setFillColor(15, 23, 42);
      pdf.rect(0, 0, w, 45, "F");
      pdf.setTextColor(16, 185, 129);
      pdf.setFontSize(22);
      pdf.setFont("helvetica", "bold");
      pdf.text("DustVision AI", 20, 22);
      pdf.setFontSize(10);
      pdf.setTextColor(148, 163, 184);
      pdf.text("Environmental Impact Assessment Report", 20, 32);
      pdf.text(`Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, 20, 39);

      let y = 60;

      // Site image
      if (data?.image) {
        try {
          pdf.addImage(data.image, "JPEG", 20, y, 80, 60);
          y += 70;
        } catch {
          // skip if image can't be added
        }
      }

      // Analysis Summary
      pdf.setTextColor(30, 41, 59);
      pdf.setFontSize(16);
      pdf.setFont("helvetica", "bold");
      pdf.text("Analysis Summary", 20, y);
      y += 10;

      pdf.setFontSize(11);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(71, 85, 105);

      const type = data?.type || "Construction";
      const score = data?.score ?? 5.0;

      pdf.text(`Site Category: ${type}`, 20, y); y += 7;
      pdf.text(`Dust Risk Score: ${score.toFixed(1)} / 10.0`, 20, y); y += 7;

      const riskLevel = score <= 3 ? "Low Risk" : score <= 6 ? "Moderate Risk" : "High Risk";
      pdf.text(`Risk Level: ${riskLevel}`, 20, y); y += 14;

      // AQI Data
      pdf.setFontSize(16);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(30, 41, 59);
      pdf.text("Air Quality Data", 20, y); y += 10;

      pdf.setFontSize(11);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(71, 85, 105);
      pdf.text("AQI: 127 (Unhealthy for Sensitive Groups)", 20, y); y += 7;
      pdf.text("PM2.5: 42.3 ug/m\u00B3", 20, y); y += 7;
      pdf.text("PM10: 78.6 ug/m\u00B3", 20, y); y += 14;

      // Mitigation Steps
      pdf.setFontSize(16);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(30, 41, 59);
      pdf.text("Recommended Mitigation Steps", 20, y); y += 10;

      pdf.setFontSize(11);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(71, 85, 105);

      const solutions = data?.solutions || [
        "Install automated water suppression systems",
        "Deploy wind barriers around the construction perimeter",
        "Implement real-time PM2.5 monitoring with IoT sensors",
      ];

      solutions.forEach((sol, i) => {
        const lines = pdf.splitTextToSize(`${i + 1}. ${sol}`, w - 40);
        pdf.text(lines, 20, y);
        y += lines.length * 6 + 4;
      });

      y += 6;
      // Footer
      pdf.setDrawColor(16, 185, 129);
      pdf.setLineWidth(0.5);
      pdf.line(20, y, w - 20, y);
      y += 8;
      pdf.setFontSize(9);
      pdf.setTextColor(148, 163, 184);
      pdf.text("This report was generated by DustVision AI — Environmental Impact Monitoring Platform", 20, y);

      pdf.save("DustVision-AI-Report.pdf");
      setDone(true);
      setTimeout(() => setDone(false), 3000);
    } catch (err) {
      console.error("PDF generation failed:", err);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <motion.button
      onClick={generate}
      disabled={generating}
      whileHover={{ scale: 1.02 }}
      whileTap={{ scale: 0.98 }}
      className="w-full py-3.5 rounded-xl glass border-primary/20 text-foreground font-semibold flex items-center justify-center gap-2.5 hover:border-primary/40 transition-all disabled:opacity-50"
    >
      {generating ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin text-primary" />
          <span className="text-sm">Generating Report...</span>
        </>
      ) : done ? (
        <>
          <CheckCircle className="w-4 h-4 text-primary" />
          <span className="text-sm">Report Downloaded!</span>
        </>
      ) : (
        <>
          <FileDown className="w-4 h-4 text-primary" />
          <span className="text-sm">Download Environmental Impact Report (PDF)</span>
        </>
      )}
    </motion.button>
  );
};

export default ReportGenerator;
